#security sections#
app_login:
        path: /login
        controller: App\Controller\SecurityController::login

security_register:
        path: /register
        controller: App\Controller\SecurityController::register

#personal sections#
personal:
      path: /personal
      controller: App\Controller\PersonalController:index

personal_basket:
        path: /basket
        controller: App\Controller\PersonalController:basket

personal_order:
        path: /order
        controller: App\Controller\PersonalController:order

#portal sections#
portal:
        path: /
        controller: App\Controller\PortalController::index

portal_contact:
        path: /contact
        controller: App\Controller\PortalController::contact

portal_news:
        path: /news/{page}
        controller: App\Controller\NewsController::news
        defaults:
              page: 1
        requirements:
              page: \d+


portal_news_detail:
        path: /news/{symlink}
        controller: App\Controller\NewsController::newsDetail

portal_catalog:
        path: /catalog
        controller: App\Controller\CatalogController::catalog

portal_catalog_section:
        path: /catalog/{section}
        controller: App\Controller\CatalogController::catalogSection
        requirements:
          detail: \d+
          section: \d+

portal_catalog_detail:
        path: /catalog/{section}/{detail}
        controller: App\Controller\CatalogController::catalogDetail
        requirements:
          detail: \d+
          section: \d+


#administation sections#
admin:
        path: /admin
        controller: App\Controller\AdminController::index

admin_table:
        path: /admin/table/{table_name}
        controller: App\Controller\AdminController::tableView
        defaults:
            table_name: "news"

admin_table_new:
        path: /admin/table/{table_name}/new
        controller: App\Controller\AdminController::tableNew

admin_table_edit:
        path: /admin/table/{table_name}/edit/{id}
        controller: App\Controller\AdminController::tableEdit
        requirements:
          id: '\d+'